# Generated by Django 3.2.15 on 2022-09-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220915_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
